## NUMPY

Multidimentional Arrays 

Why do we use Numpy over lists
- Numpy is of fixed type and its faster as well
- List uses size, reference count, object type, object value  does the same but we can change and take specific bytes as well
- Numpy uses int32 to represent any number in binary numpy
- Numpy uses less bytes of memory
- No type checking while iterating in numpy


BENEFITS
- SIMD Vector processing
- Effective Cache utilization

Application of numpy
- Mathematics (MATLAB)
- Plotting (Matplotlib)
- Backend (Pandas, Connect 4, Digital Photography)
- Machine learning

#### Load in NumPy

In [1]:
import numpy as np

#### The basics

In [9]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3])

In [4]:
b = np.array([[1,3,5,7,8],[1,2,3,4,5]])
b

array([[1, 3, 5, 7, 8],
       [1, 2, 3, 4, 5]])

#### Get Dimension

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a.dtype

dtype('int32')

In [8]:
a.itemsize

4

Accessing/Changing specific elements, rows, columns etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [11]:
# Get a specific element [r,c]
a[1,5]

13

In [12]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [14]:
#Getting a little more fancy
a[0,1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [16]:
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# Get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [20]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]

In [21]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing Different Types of Arrays

In [23]:
# All 0z matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# A;; 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [25]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [26]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Random decimal number
np.random.rand(4,2)

array([[0.26259349, 0.72701815],
       [0.17973024, 0.71175382],
       [0.8282777 , 0.86047576],
       [0.39503366, 0.59789562]])

In [28]:
np.random.rand(4,2,3)

array([[[0.87097145, 0.42383742, 0.47791475],
        [0.7814735 , 0.97031534, 0.61037121]],

       [[0.23390137, 0.39237374, 0.3274002 ],
        [0.14462255, 0.97173453, 0.19057508]],

       [[0.1819138 , 0.47217788, 0.91667017],
        [0.20056351, 0.06894322, 0.25321345]],

       [[0.76444786, 0.35661461, 0.04724717],
        [0.11890159, 0.30755301, 0.63111732]]])

In [29]:
np.random.random_sample((4,2))

array([[0.59052142, 0.94433068],
       [0.57608354, 0.50248621],
       [0.01438354, 0.46193515],
       [0.52488992, 0.22711688]])

In [30]:
# Random Integer values
np.random.randint(4,7, size=(3,3))

array([[5, 5, 6],
       [6, 5, 6],
       [5, 4, 6]])

In [31]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [35]:
output = np.ones((5,5))
output

z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Be careful when copying arrays!!!

In [36]:
a = np.array([1,2,3])
b = a
b[0] = 100

a

array([100,   2,   3])

In [37]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

a

array([1, 2, 3])

#### Mathematics

In [38]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [39]:
a+=2
a

array([3, 4, 5, 6])

In [40]:
a-2

array([1, 2, 3, 4])

In [41]:
a+2

array([5, 6, 7, 8])

In [42]:
a*2

array([ 6,  8, 10, 12])

In [43]:
a/2

array([1.5, 2. , 2.5, 3. ])

In [44]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [45]:
a ** 2

array([ 9, 16, 25, 36])

In [46]:
# Take the sin
np.cos(0)

1.0

#### Linear Algebra

In [47]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),3)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [48]:
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [49]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.min(stats)

1

In [51]:
np.max(stats)

6

In [52]:
np.sum(stats,axis=0)

array([5, 7, 9])

#### Recognizing arrays

In [53]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

##### Miscellaneous 

Load data from file

In [ ]:
filedata = np.genfromtxt('data.txt', delimeter=',')
filedata = filedata.astype('int32')
filedata

Booolean masking

In [1]:
filedata > 50

In [ ]:
np.all(filedata > 50, axis=0)

##### Indexing

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])